# Generated by Django 3.1.4 on 2023-09-13 13:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridmodel',
            name='img_vis_crop',
            field=models.ImageField(blank=True, default='/Users/Tom/Python_Projects/pep_genie/app/dummy.png', null=True, upload_to=app.models.fileFormat),
        ),
    ]
