# Generated by Django 3.1.4 on 2023-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230913_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridmodel',
            name='strip_request_string',
            field=models.CharField(default='A08-T08,A09-T09', max_length=1000),
        ),
    ]
