# Generated by Django 3.1.4 on 2023-12-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gridmodel_strip_request_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridmodel',
            name='measure_radius',
            field=models.IntegerField(default=70),
        ),
    ]
