# Generated by Django 3.1.4 on 2023-12-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gridmodel_measure_radius'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gridmodel',
            old_name='measure_radius',
            new_name='measure_diameter',
        ),
    ]
